<% local_config = File.join(Rails.root, 'config/app_config_local.yml') %>
<% if File.exists?(local_config) %>
<%= File.open(local_config).read %>
<% else %>
local_config: &local_config
  nothing: here
<% end %>
  
_shared_company_config: &_shared_company_config
  lxd:
    sales_order_quantity: "%.0f"
    google_analytics_key: UA-25625566-1
    email_name: LXD WebBot
    email_address: tharrison@lxdinc.com
    email_domain: lxdinc.com
    website: www.lxdinc.com
    company_name: LXD Research &amp; Display
    hostname: <%= Rails.env.production? ? 'm2mhub.lxdinc.com' : 'lxd_m2mhub.dev' %>
  smt:
    sales_order_quantity: "%.1f"
    google_analytics_key:
    email_name: SMT WebBot
    email_address: tharrison@smtcoinc.com
    email_domain: smtcoinc.com
    website: www.smtcoinc.com
    company_name: SMT, Inc.
    hostname: <%= Rails.env.production? ? 'm2mhub.smtcoinc.com' : 'lxd_m2mhub.dev' %>

development:
  <<: *local_config
  shared_company_config:
    <<: *_shared_company_config
  company_config:
    lxd:
    smt:
  
production:
  <<: *local_config
  shared_company_config:
    <<: *_shared_company_config
  
test:
  <<: *local_config
  shared_company_config:
    <<: *_shared_company_config

