<% local_company_config = File.join(Rails.root, 'config/local_company_config.yml') %>
<% if File.exists?(local_company_config) %>
<%= File.open(local_company_config).read %>
<% else %>
_local_company_config: &_local_company_config
  nothing: here
<% end %>
  
_shared_company_config: &_shared_company_config
  lxd:
    rounded_dollars: "%.0f"
    dollars: "%.2f"
    sales_order_quantity: "%.0f"
    item_quantity: "%.0f"
    google_analytics_key: UA-25768569-1
    email_name: LXD WebBot
    email_address: webmin@lxdinc.com
    email_domain: lxdinc.com
    website: www.lxdinc.com
    company_name: LXD Research &amp; Display
    hostname: <%= Rails.env.production? ? 'm2mhub.lxdinc.com' : 'staging.lxdinc.com' %>
  smt:
    rounded_dollars: "%.0f"
    dollars: "%.2f"
    sales_order_quantity: "%.1f"
    item_quantity: "%.1f"
    google_analytics_key:
    email_name: SMT WebBot
    email_address: tharrison@smtcoinc.com
    email_domain: smtcoinc.com
    website: www.smtcoinc.com
    company_name: SMT, Inc.
    hostname: <%= Rails.env.production? ? 'm2mhub.smtcoinc.com' : 'staging.smtcoinc.com' %>

development:
  local_company_config:
    <<: *_local_company_config
  shared_company_config:
    <<: *_shared_company_config
  company_config:
    lxd:
    smt:
  
production:
  local_company_config:
    <<: *_local_company_config
  shared_company_config:
    <<: *_shared_company_config
  company_config:
    lxd:
    smt:
  
test:
  local_company_config:
    <<: *_local_company_config
  shared_company_config:
    <<: *_shared_company_config
  company_config:
    lxd:
    smt:
