<% local_company_config = File.join(Rails.root, 'config/local_company_config.yml') %>
<% if File.exists?(local_company_config) %>
<%= File.open(local_company_config).read %>
<% else %>
_local_company_config: &_local_company_config
  nothing: here
<% end %>

_default_company_config: &_default_company_config
  otd_grace_period_days: 5
  rounded_dollars: "%.0f"
  dollars: "%.2f"
  sales_order_quantity: "%.0f"
  purchase_order_quantity: "%.0f"
  item_quantity: "%.0f"
  rma_quantity: "%.0f"
  job_quantity: "%.0f"
  quality_credit_memo_quantity: "%.0f"
  quality_credit_memo_percentage: "%0.2f"
  work_center_load_percentage: "%.0f"
  work_center_load: "%.1f"
  epoch_year: 2000
  customer_service_log_field_rma_number: fcinqno
  customer_service_log_field_credit_memo_reference: user_defined1
  
_shared_company_config: &_shared_company_config
  lxd:
    google_analytics_key: UA-25768569-1
    email_name: LXD WebBot
    email_address: webmin@lxdinc.com
    email_domain: lxdinc.com
    website: www.lxdinc.com
    short_name: LXD
    long_name: LXD Research &amp; Display
    hostname: <%= Rails.env.production? ? 'm2mhub.lxdinc.com' : 'staging.lxdinc.com' %>
    epoch_year: 2010
    customer_service_log_field_rma_id: other2
    fob_groups:
      - id: 1
        name: Raleigh
        default: true
        members:
          - our plant
          - raleigh nc
          - yd
      - id: 2
        name: China
        members:
          - HK
          - SHANGHAI
          - DDU:INDIA
          - SHIJIAZHU
          - CIF:BEIJI
          - CIF:HK
          - CIF:KOREA
          - BEIJING
    
  smt:
    google_analytics_key:
    email_name: SMT WebBot
    email_address: smtcoinc@gmail.com
    email_domain: smtcoinc.com
    website: www.smtcoinc.com
    short_name: SMT
    long_name: SMT, Inc.
    hostname: <%= Rails.env.production? ? 'm2mhub.smtcoinc.com' : 'staging.smtcoinc.com' %>
    fob_groups:
      - id: 1
        default: true
        name: SMT
        members:
          - our plant
      - id: 2
        name: Third Party
        members:
          - 3rd party
      - id: 3
        name: Your Dock
        members:
          - your dock

development:
  local_company_config:
    <<: *_local_company_config
  shared_company_config:
    <<: *_shared_company_config
  default_company_config:
    <<: *_default_company_config
  
production:
  local_company_config:
    <<: *_local_company_config
  shared_company_config:
    <<: *_shared_company_config
  default_company_config:
    <<: *_default_company_config
  
test:
  local_company_config:
    <<: *_local_company_config
  shared_company_config:
    <<: *_shared_company_config
  default_company_config:
    <<: *_default_company_config
