_local_company_config: &_local_company_config
  lxd:
    email_password: secret
    lighthouse_account: secret
    lighthouse_customer_service_project_id: secret
    lighthouse_rma_project_id: secret
    lighthouse_token: secret
    lighthouse_rma_milestone_id: secret
    lighthouse_sales_leads_id: secret
    doogle_bucket: secret
    doogle_access_key_id: secret
    doogle_secret_access_key: secret
    mailchimp_list_id: secret
    mailchimp_api_key: secret
  smt:
    email_password: