# Leave this file alone.
<% local_config = File.join(Rails.root, 'config/local_onfig.yml') %>
<% if File.exists?(local_config) %>
<%= File.open(local_config).read %>
<% else %>
local_config: &local_config
  nothing: here
<% end %>
<% app_config = File.join(Rails.root, 'config/app_config.yml') %>
<%= File.open(app_config).read if File.exists?(app_config) %>
<% m2m_config = File.join(Rails.root, 'config/m2mhub_config.yml') %>
<%= File.open(m2m_config).read if File.exists?(m2m_config) %>
